version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/predict/
    depends_on:
      - backend
  
